// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package calc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// CalcClient is the client API for Calc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalcClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	SumSequence(ctx context.Context, opts ...grpc.CallOption) (Calc_SumSequenceClient, error)
}

type calcClient struct {
	cc grpc.ClientConnInterface
}

func NewCalcClient(cc grpc.ClientConnInterface) CalcClient {
	return &calcClient{cc}
}

func (c *calcClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calc.Calc/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcClient) SumSequence(ctx context.Context, opts ...grpc.CallOption) (Calc_SumSequenceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calc_serviceDesc.Streams[0], "/calc.Calc/SumSequence", opts...)
	if err != nil {
		return nil, err
	}
	x := &calcSumSequenceClient{stream}
	return x, nil
}

type Calc_SumSequenceClient interface {
	Send(*SequenceRequest) error
	CloseAndRecv() (*SequenceResponse, error)
	grpc.ClientStream
}

type calcSumSequenceClient struct {
	grpc.ClientStream
}

func (x *calcSumSequenceClient) Send(m *SequenceRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calcSumSequenceClient) CloseAndRecv() (*SequenceResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SequenceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalcServer is the server API for Calc service.
// All implementations must embed UnimplementedCalcServer
// for forward compatibility
type CalcServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	SumSequence(Calc_SumSequenceServer) error
	mustEmbedUnimplementedCalcServer()
}

// UnimplementedCalcServer must be embedded to have forward compatible implementations.
type UnimplementedCalcServer struct {
}

func (UnimplementedCalcServer) Sum(context.Context, *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedCalcServer) SumSequence(Calc_SumSequenceServer) error {
	return status.Errorf(codes.Unimplemented, "method SumSequence not implemented")
}
func (UnimplementedCalcServer) mustEmbedUnimplementedCalcServer() {}

// UnsafeCalcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalcServer will
// result in compilation errors.
type UnsafeCalcServer interface {
	mustEmbedUnimplementedCalcServer()
}

func RegisterCalcServer(s grpc.ServiceRegistrar, srv CalcServer) {
	s.RegisterService(&_Calc_serviceDesc, srv)
}

func _Calc_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.Calc/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calc_SumSequence_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalcServer).SumSequence(&calcSumSequenceServer{stream})
}

type Calc_SumSequenceServer interface {
	SendAndClose(*SequenceResponse) error
	Recv() (*SequenceRequest, error)
	grpc.ServerStream
}

type calcSumSequenceServer struct {
	grpc.ServerStream
}

func (x *calcSumSequenceServer) SendAndClose(m *SequenceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calcSumSequenceServer) Recv() (*SequenceRequest, error) {
	m := new(SequenceRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Calc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calc.Calc",
	HandlerType: (*CalcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _Calc_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SumSequence",
			Handler:       _Calc_SumSequence_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto_files/calc.proto",
}
